[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short --strict-markers -p no:warnings
markers =
    django_db: Marca tests que requieren base de datos
    slow: Tests lentos (integración)
