# Generated by Django 5.2.14 on 2026-05-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Acta de Reunión',
                'verbose_name_plural': 'Actas de Reuniones',
            },
        ),
        migrations.CreateModel(
            name='ComunicadoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Comunicado Interno',
                'verbose_name_plural': 'Comunicados Internos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuraciones WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='EnvioWhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Log Envío WhatsApp',
                'verbose_name_plural': 'Logs Envíos WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Historial Estado Miembro',
                'verbose_name_plural': 'Historial Estados Miembros',
            },
        ),
        migrations.CreateModel(
            name='LecturaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicado_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lectura de Comunicado',
                'verbose_name_plural': 'Lecturas de Comunicados',
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='SolicitudTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Solicitud de Trámite',
                'verbose_name_plural': 'Solicitudes de Trámites',
            },
        ),
        migrations.CreateModel(
            name='VisitaIglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Visita de Iglesia',
                'verbose_name_plural': 'Visitas de Iglesias',
            },
        ),
    ]
