# Generated by Django 5.2.14 on 2026-05-26 22:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministerios', '0015_add_inventario_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_jid', models.CharField(blank=True, max_length=100)),
                ('hora_envio', models.TimeField(default=datetime.time(9, 0))),
                ('activo', models.BooleanField(default=False)),
                ('rotacion_index', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='secretaria/whatsapp/')),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ActaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('junta_directiva', 'Junta Directiva'), ('concilio', 'Concilio'), ('comite', 'Comité'), ('otra', 'Otra')], max_length=30)),
                ('fecha_reunion', models.DateField()),
                ('hora_reunion', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('presidida_por', models.CharField(blank=True, max_length=100)),
                ('asistentes', models.JSONField(default=list)),
                ('orden_del_dia', models.JSONField(default=list)),
                ('acuerdos', models.JSONField(default=list)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('archivada', 'Archivada')], default='borrador', max_length=20)),
                ('aprobada_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acta de Reunión',
                'verbose_name_plural': 'Actas de Reunión',
                'ordering': ['-fecha_reunion'],
            },
        ),
        migrations.CreateModel(
            name='ComunicadoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('destinatarios', models.CharField(choices=[('todos', 'Todos'), ('lideres', 'Líderes'), ('ministerio', 'Ministerio Específico'), ('roles', 'Por Roles')], default='todos', max_length=30)),
                ('roles_destino', models.JSONField(default=list)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='secretaria/comunicados/')),
                ('requiere_confirmacion', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_creados', to=settings.AUTH_USER_MODEL)),
                ('ministerios_destino', models.ManyToManyField(blank=True, related_name='comunicados', to='ministerios.ministerio')),
            ],
            options={
                'verbose_name': 'Comunicado Interno',
                'verbose_name_plural': 'Comunicados Internos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('ingreso', 'Ingreso'), ('transferencia_entrada', 'Transferencia Entrada'), ('transferencia_salida', 'Transferencia Salida'), ('bautismo', 'Bautismo'), ('disciplina', 'Proceso Disciplinario'), ('restauracion', 'Restauración'), ('retiro_voluntario', 'Retiro Voluntario'), ('fallecimiento', 'Fallecimiento'), ('otra', 'Otra Anotación')], max_length=30)),
                ('fecha_evento', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('iglesia_origen', models.CharField(blank=True, max_length=200)),
                ('iglesia_destino', models.CharField(blank=True, max_length=200)),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='secretaria/historial/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documentado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_documentado', to=settings.AUTH_USER_MODEL)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estado', to='ministerios.miembro')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Miembro',
                'verbose_name_plural': 'Historial de Estados de Miembro',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='EnvioWhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_enviado', models.TextField()),
                ('grupo_jid', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], max_length=10)),
                ('error_detalle', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='secretaria.mensajewhatsapp')),
            ],
            options={
                'verbose_name': 'Log de Envío WhatsApp',
                'verbose_name_plural': 'Logs de Envíos WhatsApp',
                'ordering': ['-enviado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('membresia', 'Solicitud de Membresía'), ('carta_recomendacion', 'Carta de Recomendación'), ('carta_membresia', 'Carta de Membresía'), ('transferencia', 'Transferencia de Membresía'), ('bautismo', 'Bautismo'), ('matrimonio', 'Matrimonio'), ('retiro', 'Retiro Voluntario'), ('otra', 'Otra Solicitud')], max_length=30)),
                ('solicitante_nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('datos_adicionales', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('resolucion_notas', models.TextField(blank=True)),
                ('documento_generado', models.FileField(blank=True, null=True, upload_to='secretaria/solicitudes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_atendidas', to=settings.AUTH_USER_MODEL)),
                ('ministerio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_secretaria', to='ministerios.ministerio')),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_registradas', to=settings.AUTH_USER_MODEL)),
                ('solicitante_miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='ministerios.miembro')),
            ],
            options={
                'verbose_name': 'Solicitud / Trámite',
                'verbose_name_plural': 'Solicitudes / Trámites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitaIglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_primera_visita', models.DateField()),
                ('cantidad_visitas', models.PositiveIntegerField(default=1)),
                ('ultima_visita', models.DateField(blank=True, null=True)),
                ('seguimiento', models.CharField(choices=[('sin_seguimiento', 'Sin Seguimiento'), ('contactado', 'Contactado'), ('integrado', 'Integrado a Ministerio'), ('no_regreso', 'No Regresó')], default='sin_seguimiento', max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('convertido_miembro', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miembro_vinculado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visita_origen', to='ministerios.miembro')),
                ('ministerio_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='ministerios.ministerio')),
                ('responsable_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha_primera_visita'],
            },
        ),
        migrations.CreateModel(
            name='LecturaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido_en', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='secretaria.comunicadointerno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_comunicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de Comunicado',
                'unique_together': {('comunicado', 'usuario')},
            },
        ),
    ]
