# Generated by Django 5.2.14 on 2026-05-22 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFinanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_distrital_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de PRES.DISTRITAL (ej: 10.00 = 10%)', max_digits=5)),
                ('pres_educacional_pct', models.DecimalField(decimal_places=2, default=3.0, help_text='Porcentaje de PRES EDUCACIONAL (ej: 3.00 = 3%)', max_digits=5)),
                ('pres_evangelismo_pct', models.DecimalField(decimal_places=2, default=2.0, help_text='Porcentaje de PRES.EVANGELISMO (ej: 2.00 = 2%)', max_digits=5)),
                ('jubilacion_monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo de jubilación mensual', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Finanzas',
                'verbose_name_plural': 'Configuración de Finanzas',
            },
        ),
        migrations.CreateModel(
            name='InformeMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('datos', models.JSONField(help_text='Estructura completa del informe mensual')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe Mensual',
                'verbose_name_plural': 'Informes Mensuales',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
