# Generated by Django 5.2.14 on 2026-05-22 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0004_ofrenda_categoria_alter_miembro_origen'),
        ('tesoreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionfinanzas',
            options={'verbose_name': 'Configuracion de Finanzas', 'verbose_name_plural': 'Configuracion de Finanzas'},
        ),
        migrations.AlterField(
            model_name='configuracionfinanzas',
            name='jubilacion_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo de jubilacion mensual', max_digits=12),
        ),
        migrations.CreateModel(
            name='MovimientoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso_diezmo', 'Diezmo'), ('ingreso_especial', 'Donacion Especial'), ('ingreso_ahorro', 'Ahorro'), ('ingreso_proyectos', 'Proyectos'), ('egreso_sosten_pastoral', 'Sosten Pastoral'), ('egreso_beneficios_pastorales', 'Beneficios Pastorales'), ('egreso_varios_iglesia', 'Gastos Varios Iglesia'), ('egreso_fondo_contingencia', 'Fondo de Contingencia')], max_length=35)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tesoreria/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Tesoreria',
                'verbose_name_plural': 'Movimientos de Tesoreria',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuotaFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coce', 'COCE'), ('cuota_distrital', 'Cuota Distrital')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_fijas', to='ministerios.ministerio')),
            ],
            options={
                'verbose_name': 'Cuota Fija',
                'verbose_name_plural': 'Cuotas Fijas',
                'unique_together': {('ministry', 'tipo')},
            },
        ),
    ]
