# Generated by Django 5.2.14 on 2026-05-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_alter_configuracionfinanzas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfinanzas',
            name='ciudad',
            field=models.CharField(default='ARICA', help_text='Ciudad de la iglesia', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionfinanzas',
            name='nombre_distrito',
            field=models.CharField(default='Distrito Norte de Chile', help_text='Nombre del distrito para los informes', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionfinanzas',
            name='nombre_iglesia',
            field=models.CharField(default='Iglesia del Nazareno "Juan Noe"', help_text='Nombre de la iglesia para los informes', max_length=200),
        ),
    ]
