# Generated by Django 5.2.14 on 2026-05-26 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0007_inventario_imagen'),
        ('tesoreria', '0003_configuracionfinanzas_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientotesoreria',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_tesoreria', to='ministerios.ministerio'),
        ),
        migrations.AlterField(
            model_name='movimientotesoreria',
            name='tipo',
            field=models.CharField(choices=[('ingreso_diezmo', 'Diezmo'), ('ingreso_especial', 'Donacion Especial'), ('ingreso_ofrenda', 'Ofrenda'), ('ingreso_ahorro', 'Ahorro'), ('ingreso_proyectos', 'Proyectos'), ('egreso_sosten_pastoral', 'Sosten Pastoral'), ('egreso_beneficios_pastorales', 'Beneficios Pastorales'), ('egreso_varios_iglesia', 'Gastos Varios Iglesia'), ('egreso_fondo_contingencia', 'Fondo de Contingencia')], max_length=35),
        ),
    ]
