# Generated by Django 5.2.14 on 2026-05-26 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0010_set_aprobado_true_for_existing'),
        ('tesoreria', '0004_add_ingreso_ofrenda_and_ministry_to_movimientotesoreria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_tipo', models.CharField(max_length=20)),
                ('entidad_id', models.IntegerField()),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('eliminado', 'Eliminado')], max_length=20)),
                ('resumen', models.CharField(blank=True, help_text='Resumen legible de la acción', max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministerios.ministerio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
