# Generated by Django 5.2.14 on 2026-05-07 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cancion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("artista", models.CharField(blank=True, max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("rapida", "Rápida"),
                            ("media", "Media"),
                            ("lenta", "Lenta"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tono", models.CharField(blank=True, max_length=10)),
                ("letra", models.TextField(blank=True)),
                ("acordes", models.TextField(blank=True)),
                ("link_youtube", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Canción",
                "verbose_name_plural": "Canciones",
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="LeccionEXPLO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("contenido", models.TextField(blank=True)),
                ("link_material", models.URLField(blank=True)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="explo/lecciones/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lección EXPLO",
                "verbose_name_plural": "Lecciones EXPLO",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ministerio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("icono", models.CharField(default="church", max_length=50)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ministerio",
                "verbose_name_plural": "Ministerios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("permisos", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="Miembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primer_nombre", models.CharField(max_length=50)),
                ("segundo_nombre", models.CharField(blank=True, max_length=50)),
                ("primer_apellido", models.CharField(max_length=50)),
                ("segundo_apellido", models.CharField(blank=True, max_length=50)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("edad", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soltero", "Soltero/a"),
                            ("casado", "Casado/a"),
                            ("viudo", "Viudo/a"),
                            ("divorciado", "Divorciado/a"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                (
                    "clase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ninos", "Niños (0-12)"),
                            ("jovenes", "Jóvenes (13-17)"),
                            ("adultos_jovenes", "Adultos Jóvenes (18-35)"),
                            ("adultos", "Adultos (36-60)"),
                            ("adultos_mayores", "Adultos Mayores (60+)"),
                        ],
                        help_text="Solo para DNI",
                        max_length=20,
                    ),
                ),
                (
                    "rol_en_ministerio",
                    models.CharField(
                        choices=[
                            ("miembro", "Miembro"),
                            ("lider", "Líder"),
                            ("sublider", "Sublíder"),
                            ("tesorero", "Tesorero"),
                            ("secretario", "Secretario"),
                        ],
                        default="miembro",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_ingreso", models.DateField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="miembros_en_ministerios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to="ministerios.ministerio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro",
                "verbose_name_plural": "Miembros",
                "ordering": ["primer_apellido", "primer_nombre"],
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("muebles", "Muebles"),
                            ("electronicos", "Electrónicos"),
                            ("decoracion", "Decoración"),
                            ("utensilios", "Utensilios"),
                            ("musica", "Música"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("ubicacion", models.CharField(blank=True, max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nuevo", "Nuevo"),
                            ("bueno", "Bueno"),
                            ("regular", "Regular"),
                            ("mal_estado", "Mal Estado"),
                        ],
                        default="bueno",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="ministerios.ministerio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="IdeaComunicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("completada", models.BooleanField(default=False)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to="ministerios.ministerio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Idea de Comunicación",
                "verbose_name_plural": "Ideas de Comunicación",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_inicio", models.DateTimeField()),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("propio", "Propio"), ("compartido", "Compartido")],
                        default="propio",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ministerios_relacionados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="eventos_compartidos",
                        to="ministerios.ministerio",
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="ministerios.ministerio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="CajaMinisterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ministry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caja",
                        to="ministerios.ministerio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja de Ministerio",
                "verbose_name_plural": "Cajas de Ministerios",
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("presente", models.BooleanField(default=False)),
                ("es_visita", models.BooleanField(default=False)),
                ("nombre_visita", models.CharField(blank=True, max_length=100)),
                ("clase", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "miembro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="ministerios.miembro",
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="ministerios.ministerio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "ordering": ["-fecha", "clase"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="cajas/boletas/"
                    ),
                ),
                ("enviado_tesoreria", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="ministerios.cajaministerio",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Caja",
                "verbose_name_plural": "Movimientos de Caja",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Ofrenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "clase",
                    models.CharField(
                        blank=True,
                        help_text="Para DNI - clase específica",
                        max_length=30,
                    ),
                ),
                ("envidada_tesoreria", models.BooleanField(default=False)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofrendas",
                        to="ministerios.ministerio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ofrenda",
                "verbose_name_plural": "Ofrendas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("pastora", "Pastora"),
                            ("secretaria", "Secretaria"),
                            ("tesorera", "Tesorera"),
                            ("lider_ministerio", "Líder de Ministerio"),
                            ("concilio", "Concilio"),
                        ],
                        default="concilio",
                        max_length=20,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="usuarios/fotos/"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "ministerios_lidera",
                    models.ManyToManyField(
                        blank=True, related_name="lideres", to="ministerios.ministerio"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
            },
        ),
        migrations.CreateModel(
            name="ProgramaAlabanza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "alabanzas",
                    models.JSONField(
                        default=list, help_text="Lista de canciones ordenadas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programas",
                        to="ministerios.ministerio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de Alabanza",
                "verbose_name_plural": "Programas de Alabanza",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="RecursoComunicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("colorimetria", "Colorimetría"),
                            ("plantilla", "Plantilla"),
                            ("imagen", "Imagen"),
                            ("video", "Video"),
                            ("logo", "Logo"),
                            ("documento", "Documento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("archivo", models.FileField(upload_to="comunicaciones/recursos/")),
                ("url_externa", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos",
                        to="ministerios.ministerio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso de Comunicación",
                "verbose_name_plural": "Recursos de Comunicación",
                "ordering": ["-created_at"],
            },
        ),
    ]
