# Generated by Django 5.2.14 on 2026-05-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerio',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
