# Generated by Django 5.2.8 on 2026-05-08 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ministerios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="observaciones",
            field=models.TextField(blank=True, help_text="Observaciones adicionales"),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="tiene_biblia",
            field=models.BooleanField(
                default=False, help_text="Indica si el asistente tiene Biblia"
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="permisos_especificos",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="ultimo_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("miembros", "Miembros"),
                            ("asistencia", "Asistencia"),
                            ("caja", "Caja"),
                            ("inventario", "Inventario"),
                            ("eventos", "Eventos"),
                            ("planificaciones", "Planificaciones"),
                            ("usuarios", "Gestión de Usuarios"),
                            ("reportes", "Reportes"),
                            ("ofrendas", "Ofrendas"),
                        ],
                        max_length=30,
                    ),
                ),
                ("acciones", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "unique_together": {("nombre", "modulo")},
            },
        ),
        migrations.CreateModel(
            name="PlanificacionActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_planificada", models.DateField()),
                ("hora", models.TimeField(blank=True, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("propia", "Propia"), ("compartida", "Compartida")],
                        default="propia",
                        max_length=10,
                    ),
                ),
                (
                    "presupuesto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificada", "Planificada"),
                            ("en_proceso", "En Proceso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="planificada",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ministerios_relacionados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planificaciones_compartidas",
                        to="ministerios.ministerio",
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planificaciones",
                        to="ministerios.ministerio",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planificación de Actividad",
                "verbose_name_plural": "Planificaciones de Actividades",
                "ordering": ["-fecha_planificada"],
            },
        ),
    ]
