# Generated by Django 5.2.14 on 2026-05-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0002_ministerio_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('sistema', 'Sistema')], default='manual', max_length=20),
        ),
    ]
