# Generated by Django 5.2.14 on 2026-05-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0003_origen_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofrenda',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ofrenda_general', 'Ofrenda General'), ('caja_alabastro', 'Caja de Alabastro'), ('accion_gracias', 'Acción de Gracias'), ('dip', 'DIP'), ('oracion_ayuno', 'Oración y Ayuno'), ('fem', 'FEM'), ('otros', 'Otros')], help_text='Categoría de ofrenda (MNI)', max_length=30),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='origen',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('sistema', 'Sistema')], default='manual', max_length=20),
        ),
    ]
