# Generated by Django 5.2.14 on 2026-05-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0004_ofrenda_categoria_alter_miembro_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
