# Generated by Django 5.2.14 on 2026-05-26 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0005_alter_movimientocaja_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(blank=True)),
                ('color', models.CharField(default='#fef3c7', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, help_text='Evento opcional al que se vincula la nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='ministerios.evento')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='ministerios.ministerio')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-updated_at'],
            },
        ),
    ]
