# Generated by Django 5.2.14 on 2026-05-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0006_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inventario/fotos/'),
        ),
    ]
