# Generated by Django 5.2.14 on 2026-05-26 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0007_inventario_imagen'),
        ('tesoreria', '0004_add_ingreso_ofrenda_and_ministry_to_movimientotesoreria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofrenda',
            name='movimiento_tesoreria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofrenda_origen', to='tesoreria.movimientotesoreria'),
        ),
    ]
