# Generated by Django 5.2.14 on 2026-05-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0008_add_movimiento_tesoreria_fk_to_ofrenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ofrenda',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
