# Generated by Django 5.2.14 on 2026-05-26 03:32

from django.db import migrations


def set_aprobado_true(apps, schema_editor):
    MovimientoCaja = apps.get_model('ministerios', 'MovimientoCaja')
    Ofrenda = apps.get_model('ministerios', 'Ofrenda')
    MovimientoCaja.objects.all().update(aprobado=True)
    Ofrenda.objects.all().update(aprobado=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0009_add_aprobado_to_movimientocaja_and_ofrenda'),
    ]

    operations = [
        migrations.RunPython(set_aprobado_true, migrations.RunPython.noop),
    ]
