# Generated by Django 5.2.14 on 2026-05-26 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0010_set_aprobado_true_for_existing'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfoqueMNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Enfoque MNI',
                'verbose_name_plural': 'Enfoques MNI',
                'ordering': ['mes'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaUltimoDomingo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('secciones', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_domingo', to='ministerios.ministerio')),
            ],
            options={
                'verbose_name': 'Programa Último Domingo',
                'verbose_name_plural': 'Programas Último Domingo',
                'ordering': ['-fecha'],
            },
        ),
    ]
