# Generated by Django 5.2.14 on 2026-05-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0011_add_enfoques_mni_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='ofrenda_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ministerios.ofrenda'),
        ),
    ]
