# Generated by Django 5.2.14 on 2026-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0012_add_ofrenda_origen_to_movimiento_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='clase',
            field=models.CharField(blank=True, choices=[('parvulos', 'Párvulos (1-5 años)'), ('principiantes', 'Principiantes (6-10 años)'), ('primarios', 'Primarios (11-15 años)'), ('jovenes', 'Jóvenes (16-35 años)'), ('adultos', 'Adultos (35+ años)')], help_text='Solo para DNI', max_length=20),
        ),
    ]
