# Generated by Django 5.2.14 on 2026-05-26 17:57

from django.db import migrations

CLASE_MAP = {
    'ninos': 'parvulos',
    'jovenes': 'principiantes',
    'adultos_jovenes': 'primarios',
    'adultos': 'jovenes',
    'adultos_mayores': 'adultos',
}


def migrate_clases(apps, schema_editor):
    Miembro = apps.get_model('ministerios', 'Miembro')
    Asistencia = apps.get_model('ministerios', 'Asistencia')
    Ofrenda = apps.get_model('ministerios', 'Ofrenda')

    for old, new in CLASE_MAP.items():
        Miembro.objects.filter(clase=old).update(clase=new)
        Asistencia.objects.filter(clase=old).update(clase=new)
        Ofrenda.objects.filter(clase=old).update(clase=new)


def reverse_clases(apps, schema_editor):
    Miembro = apps.get_model('ministerios', 'Miembro')
    Asistencia = apps.get_model('ministerios', 'Asistencia')
    Ofrenda = apps.get_model('ministerios', 'Ofrenda')

    for old, new in CLASE_MAP.items():
        Miembro.objects.filter(clase=new).update(clase=old)
        Asistencia.objects.filter(clase=new).update(clase=old)
        Ofrenda.objects.filter(clase=new).update(clase=old)


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0013_alter_miembro_clase'),
    ]

    operations = [
        migrations.RunPython(migrate_clases, reverse_clases),
    ]
