# Generated by Django 5.2.14 on 2026-05-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0014_data_migrate_clases_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
